/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */
/* @generated by syscall_gen.py v1.0.1 from syscall.xml — DO NOT EDIT */
/* Source: include/uapi/linux/airymax/syscall.xml (R-01 SSoT) */
/*
 * Copyright (c) 2025-2026 SPHARX Ltd. All Rights Reserved.
 *
 * agentrt-linux (AirymaxOS) Agent 专用系统调用编号定义（生成产物）
 *
 * 编号规则:
 *   - 起始编号 548（避开 Linux 标准 0-511 + x86_64 x32 区域 512-547）
 *   - 4 核心 syscall + 20 预留 = 24 槽位（v1.0.1 Capability Folding）
 *   - 编号在 MAJOR 版本内不可变更（OS-IRON-001）
 *   - 废弃编号保留，返回 -AIRY_ENOSYS
 */

#ifndef AIRY_SYSCALL_GEN_H
#define AIRY_SYSCALL_GEN_H

#include <stdint.h>

/* ===== 基址与槽位计数 ===== */
#define AIRY_SYS_BASE		548  /* agentrt-linux 专用编号起始 */
#define AIRY_SYS_NR_CORE	4    /* 核心 syscall 数 */
#define AIRY_SYS_NR_RESERVED	20   /* 预留槽位数 */
#define AIRY_SYS_NR_TOTAL	24   /* 总槽位数（548-571） */

/* ===== 内部索引编号（0-3，仅 codegen 内部使用） =====
 * 注意：这些是 codegen 内部索引，与 [SC] syscalls.h 中的
 * AIRY_SYS_CALL=548 等实际系统调用号不同。为避免命名冲突，
 * 内部索引使用 AIRY_SYS_IDX_* 前缀。
 */
#define AIRY_SYS_IDX_CALL	0  /* airy_sys_call */
#define AIRY_SYS_IDX_ROVOL_CTL	1  /* airy_sys_rovol_ctl */
#define AIRY_SYS_IDX_SCHED_CTL	2  /* airy_sys_sched_ctl */
#define AIRY_SYS_IDX_CLT_NOTIFY	3  /* airy_sys_clt_notify */

/* ===== Linux 注册号（内部编号 + 548） ===== */
#define __NR_airy_sys_call	548
#define __NR_airy_sys_rovol_ctl	549
#define __NR_airy_sys_sched_ctl	550
#define __NR_airy_sys_clt_notify	551

/* ===== 预留槽位（不生成函数声明） ===== */
#define AIRY_SYS_RESERVED_4	4  /* Linux 552 */
#define AIRY_SYS_RESERVED_5	5  /* Linux 553 */
#define AIRY_SYS_RESERVED_6	6  /* Linux 554 */
#define AIRY_SYS_RESERVED_7	7  /* Linux 555 */
#define AIRY_SYS_RESERVED_8	8  /* Linux 556 */
#define AIRY_SYS_RESERVED_9	9  /* Linux 557 */
#define AIRY_SYS_RESERVED_10	10  /* Linux 558 */
#define AIRY_SYS_RESERVED_11	11  /* Linux 559 */
#define AIRY_SYS_RESERVED_12	12  /* Linux 560 */
#define AIRY_SYS_RESERVED_13	13  /* Linux 561 */
#define AIRY_SYS_RESERVED_14	14  /* Linux 562 */
#define AIRY_SYS_RESERVED_15	15  /* Linux 563 */
#define AIRY_SYS_RESERVED_16	16  /* Linux 564 */
#define AIRY_SYS_RESERVED_17	17  /* Linux 565 */
#define AIRY_SYS_RESERVED_18	18  /* Linux 566 */
#define AIRY_SYS_RESERVED_19	19  /* Linux 567 */
#define AIRY_SYS_RESERVED_20	20  /* Linux 568 */
#define AIRY_SYS_RESERVED_21	21  /* Linux 569 */
#define AIRY_SYS_RESERVED_22	22  /* Linux 570 */
#define AIRY_SYS_RESERVED_23	23  /* Linux 571 */

/* ===== 函数原型 ===== */
#ifdef __cplusplus
extern "C" {
#endif

/**
 * airy_sys_call - Unified capability invocation (sec_d 专属管理入口).
 *
 * Return: 0 on success, negative errno on failure.
 *
 * @since 1.0.1
 * @stability stable
 */
AIRY_API int airy_sys_call(cap_t cap, const struct airy_ipc_msg_hdr *msg);

/**
 * airy_sys_rovol_ctl - Reverse-of-volatility (rovol) control operations.
 *
 * Return: 0 on success, negative errno on failure.
 *
 * @since 1.0.1
 * @stability stable
 */
AIRY_API int airy_sys_rovol_ctl(uint32_t op, uint32_t pid, uint64_t arg);

/**
 * airy_sys_sched_ctl - Scheduler control operations (sched_tac policy via
 * cgroup path + policy string).
 *
 * Return: 0 on success, negative errno on failure.
 *
 * @since 1.0.1
 * @stability stable
 */
AIRY_API int airy_sys_sched_ctl(uint32_t op, const char *cgroup_path,
				const char *policy);

/**
 * airy_sys_clt_notify - CoreLoopThree phase notification + kthread control
 * (phase: PERCEPT/THINK/ACT).
 *
 * Return: 0 on success, negative errno on failure.
 *
 * @since 1.0.1
 * @stability stable
 */
AIRY_API int airy_sys_clt_notify(int task_id, uint32_t phase);

#ifdef __cplusplus
}
#endif

#endif /* AIRY_SYSCALL_GEN_H */
